// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/capcom6",
            "email": "i@capcom.me"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate with the SMSGate using basic credentials. Returns a session cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Invalidate the current session and clear the session cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Returns the login of the currently authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.meResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices": {
            "get": {
                "description": "Returns all registered devices.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "List devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.deviceListItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices/{id}": {
            "delete": {
                "description": "Removes a device by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Delete device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages": {
            "get": {
                "description": "Returns paginated list of messages with optional filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "List messages",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by state",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by device ID",
                        "name": "deviceId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (RFC3339)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (RFC3339)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.listMessagesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Sends a new text message to one or more recipients.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Send message",
                "parameters": [
                    {
                        "description": "Message to send",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.sendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smsgateway.MessageState"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/{id}": {
            "get": {
                "description": "Returns full message state by message ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Get message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smsgateway.MessageState"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "description": "Returns current device settings.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Get settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smsgateway.DeviceSettings"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates device settings. Only included fields will be changed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Update settings",
                "parameters": [
                    {
                        "description": "Settings to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/smsgateway.DeviceSettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smsgateway.DeviceSettings"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Returns aggregated statistics for the dashboard (devices, messages).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Dashboard stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dashboard.Stats"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/trends": {
            "get": {
                "description": "Returns per-day message volume and device activity for the last 7, 14, or 30 days.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Dashboard trends",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 7,
                        "description": "Number of days (7, 14, or 30)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dashboard.Trends"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tokens": {
            "post": {
                "description": "Generates a new API token with specified scopes and optional TTL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Create token",
                "parameters": [
                    {
                        "description": "Token request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smsgateway.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tokens/{jti}": {
            "delete": {
                "description": "Invalidates an API token by its JTI (token ID).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Revoke token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token JTI",
                        "name": "jti",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/webhooks": {
            "get": {
                "description": "Returns all registered webhooks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "List webhooks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.webhookListItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Registers a new webhook for the specified event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Create webhook",
                "parameters": [
                    {
                        "description": "Webhook to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createWebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/smsgateway.Webhook"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/webhooks/{id}": {
            "delete": {
                "description": "Removes a webhook by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Delete webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Webhook ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dashboard.DayActivity": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                }
            }
        },
        "dashboard.DayVolume": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "failed": {
                    "type": "integer"
                },
                "pending": {
                    "type": "integer"
                },
                "sent": {
                    "type": "integer"
                }
            }
        },
        "dashboard.Stats": {
            "type": "object",
            "properties": {
                "devicesActive": {
                    "type": "integer"
                },
                "devicesOnline": {
                    "type": "integer"
                },
                "devicesTotal": {
                    "type": "integer"
                },
                "messagesFailed": {
                    "type": "integer"
                },
                "messagesPending": {
                    "type": "integer"
                },
                "messagesSent": {
                    "type": "integer"
                }
            }
        },
        "dashboard.Trends": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "integer"
                },
                "deviceActivity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dashboard.DayActivity"
                    }
                },
                "messageVolume": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dashboard.DayVolume"
                    }
                }
            }
        },
        "fiberfx.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.createTokenRequest": {
            "type": "object",
            "required": [
                "scopes"
            ],
            "properties": {
                "scopes": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "ttl": {
                    "type": "integer"
                }
            }
        },
        "handlers.createWebhookRequest": {
            "type": "object",
            "required": [
                "event",
                "url"
            ],
            "properties": {
                "deviceId": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "handlers.deviceListItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isOnline": {
                    "type": "boolean"
                },
                "lastSeen": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handlers.listMessagesResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.messageListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.loginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.loginResponse": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                }
            }
        },
        "handlers.meResponse": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                }
            }
        },
        "handlers.messageListItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deviceId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recipients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.recipientItem"
                    }
                },
                "state": {
                    "$ref": "#/definitions/smsgateway.ProcessingState"
                },
                "textPreview": {
                    "type": "string"
                }
            }
        },
        "handlers.recipientItem": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/smsgateway.ProcessingState"
                }
            }
        },
        "handlers.sendMessageRequest": {
            "type": "object",
            "required": [
                "phoneNumbers",
                "text"
            ],
            "properties": {
                "phoneNumbers": {
                    "type": "array",
                    "maxItems": 100,
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "priority": {
                    "type": "integer",
                    "maximum": 127,
                    "minimum": -128
                },
                "simNumber": {
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 1
                },
                "text": {
                    "type": "string",
                    "maxLength": 65535,
                    "minLength": 1
                }
            }
        },
        "handlers.webhookListItem": {
            "type": "object",
            "properties": {
                "deviceId": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "smsgateway.DataMessage": {
            "type": "object",
            "required": [
                "data",
                "port"
            ],
            "properties": {
                "data": {
                    "description": "Data is the base64-encoded payload.",
                    "type": "string",
                    "format": "byte",
                    "maxLength": 65535,
                    "minLength": 4,
                    "example": "SGVsbG8gV29ybGQh"
                },
                "port": {
                    "description": "Port is the destination port.",
                    "type": "integer",
                    "maximum": 65535,
                    "minimum": 1,
                    "example": 53739
                }
            }
        },
        "smsgateway.DeviceSettings": {
            "type": "object",
            "properties": {
                "encryption": {
                    "description": "Encryption contains settings related to message encryption.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.SettingsEncryption"
                        }
                    ]
                },
                "gateway": {
                    "description": "Gateway contains settings related to the gateway.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.SettingsGateway"
                        }
                    ]
                },
                "logs": {
                    "description": "Logs contains settings related to logging.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.SettingsLogs"
                        }
                    ]
                },
                "messages": {
                    "description": "Messages contains settings related to message handling.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.SettingsMessages"
                        }
                    ]
                },
                "ping": {
                    "description": "Ping contains settings related to ping functionality.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.SettingsPing"
                        }
                    ]
                },
                "receiver": {
                    "description": "Receiver contains settings related to SMS message reception.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.SettingsReceiver"
                        }
                    ]
                },
                "webhooks": {
                    "description": "Webhooks contains settings related to webhook functionality.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.SettingsWebhooks"
                        }
                    ]
                }
            }
        },
        "smsgateway.HashedMessage": {
            "type": "object",
            "required": [
                "hash"
            ],
            "properties": {
                "hash": {
                    "type": "string",
                    "example": "1d4b6e3b1b6e3b1b6e3b1b6e3b1b6e3b1b6e3b1b"
                }
            }
        },
        "smsgateway.LimitPeriod": {
            "type": "string",
            "enum": [
                "Disabled",
                "PerMinute",
                "Per30Minutes",
                "PerHour",
                "PerDay"
            ],
            "x-enum-varnames": [
                "Disabled",
                "PerMinute",
                "Per30Minutes",
                "PerHour",
                "PerDay"
            ]
        },
        "smsgateway.MessageState": {
            "type": "object",
            "required": [
                "deviceId",
                "id",
                "recipients",
                "state"
            ],
            "properties": {
                "dataMessage": {
                    "description": "Present only when ` + "`" + `includeContent=true` + "`" + ` and the message type is data.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.DataMessage"
                        }
                    ]
                },
                "deviceId": {
                    "description": "Device ID",
                    "type": "string",
                    "maxLength": 21,
                    "example": "PyDmBQZZXYmyxMwED8Fzy"
                },
                "hashedMessage": {
                    "description": "Hashed message content, if isHashed is true",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.HashedMessage"
                        }
                    ]
                },
                "id": {
                    "description": "Message ID",
                    "type": "string",
                    "maxLength": 36,
                    "example": "PyDmBQZZXYmyxMwED8Fzy"
                },
                "isEncrypted": {
                    "description": "Encrypted",
                    "type": "boolean",
                    "example": false
                },
                "isHashed": {
                    "description": "Hashed",
                    "type": "boolean",
                    "example": false
                },
                "recipients": {
                    "description": "Recipients states",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/smsgateway.RecipientState"
                    }
                },
                "state": {
                    "description": "State",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.ProcessingState"
                        }
                    ],
                    "example": "Pending"
                },
                "states": {
                    "description": "History of states",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "textMessage": {
                    "description": "Present only when ` + "`" + `includeContent=true` + "`" + ` and the message type is text.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.TextMessage"
                        }
                    ]
                }
            }
        },
        "smsgateway.MessagesProcessingOrder": {
            "type": "string",
            "enum": [
                "LIFO",
                "FIFO"
            ],
            "x-enum-varnames": [
                "LIFO",
                "FIFO"
            ]
        },
        "smsgateway.ProcessingState": {
            "type": "string",
            "enum": [
                "Pending",
                "Cancelling",
                "Cancelled",
                "Processed",
                "Sent",
                "Delivered",
                "Failed"
            ],
            "x-enum-comments": {
                "ProcessingStateCancelled": "Cancelled",
                "ProcessingStateCancelling": "Cancelling (cancellation requested)",
                "ProcessingStateDelivered": "Delivered",
                "ProcessingStateFailed": "Failed",
                "ProcessingStatePending": "Pending",
                "ProcessingStateProcessed": "Processed (received by device)",
                "ProcessingStateSent": "Sent"
            },
            "x-enum-descriptions": [
                "Pending",
                "Cancelling (cancellation requested)",
                "Cancelled",
                "Processed (received by device)",
                "Sent",
                "Delivered",
                "Failed"
            ],
            "x-enum-varnames": [
                "ProcessingStatePending",
                "ProcessingStateCancelling",
                "ProcessingStateCancelled",
                "ProcessingStateProcessed",
                "ProcessingStateSent",
                "ProcessingStateDelivered",
                "ProcessingStateFailed"
            ]
        },
        "smsgateway.RecipientState": {
            "type": "object",
            "required": [
                "phoneNumber",
                "state"
            ],
            "properties": {
                "error": {
                    "description": "Error (for ` + "`" + `Failed` + "`" + ` state)",
                    "type": "string",
                    "example": "timeout"
                },
                "phoneNumber": {
                    "description": "Phone number or first 16 symbols of SHA256 hash",
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1,
                    "example": "79990001234"
                },
                "state": {
                    "description": "State",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.ProcessingState"
                        }
                    ],
                    "example": "Pending"
                }
            }
        },
        "smsgateway.SettingsEncryption": {
            "type": "object",
            "properties": {
                "passphrase": {
                    "description": "Passphrase is the encryption passphrase. If nil or empty, encryption is disabled. Must not be used with Cloud Server.",
                    "type": "string"
                }
            }
        },
        "smsgateway.SettingsGateway": {
            "type": "object",
            "properties": {
                "cloud_url": {
                    "description": "CloudURL is the URL of the cloud server. Must not be used with Cloud Server.",
                    "type": "string"
                },
                "notification_channel": {
                    "description": "NotificationChannel is the way device receives notifications.",
                    "type": "string",
                    "enum": [
                        "AUTO",
                        "SSE_ONLY"
                    ]
                },
                "private_token": {
                    "description": "PrivateToken is the auth token for the private server. Must not be used with Cloud Server.",
                    "type": "string"
                }
            }
        },
        "smsgateway.SettingsLogs": {
            "type": "object",
            "properties": {
                "lifetime_days": {
                    "description": "LifetimeDays is the number of days to retain logs.\nMust be at least 1 when provided.",
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "smsgateway.SettingsMessages": {
            "type": "object",
            "properties": {
                "limit_period": {
                    "description": "LimitPeriod defines the period for message sending limits.\nValid values are \"Disabled\", \"PerMinute\", \"Per30Minutes\", \"PerHour\", or \"PerDay\".",
                    "enum": [
                        "Disabled",
                        "PerMinute",
                        "Per30Minutes",
                        "PerHour",
                        "PerDay"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.LimitPeriod"
                        }
                    ]
                },
                "limit_value": {
                    "description": "LimitValue is the maximum number of messages allowed per limit period.\nMust be at least 1 when provided.",
                    "type": "integer",
                    "minimum": 1
                },
                "log_lifetime_days": {
                    "description": "LogLifetimeDays is the number of days to retain message logs.\nMust be at least 1 when provided.",
                    "type": "integer",
                    "minimum": 1
                },
                "processing_order": {
                    "description": "MessagesProcessingOrder defines the order in which messages are processed.\nValid values are \"LIFO\" or \"FIFO\".",
                    "enum": [
                        "LIFO",
                        "FIFO"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.MessagesProcessingOrder"
                        }
                    ]
                },
                "send_interval_max": {
                    "description": "SendIntervalMax is the maximum interval between message sends (in seconds).\nMust be at least 1 when provided and greater than or equal to SendIntervalMin.",
                    "type": "integer",
                    "minimum": 1
                },
                "send_interval_min": {
                    "description": "SendIntervalMin is the minimum interval between message sends (in seconds).\nMust be at least 1 when provided.",
                    "type": "integer",
                    "minimum": 1
                },
                "sim_selection_mode": {
                    "description": "SimSelectionMode defines how SIM cards are selected for sending messages.\nValid values are \"OSDefault\", \"RoundRobin\", or \"Random\".",
                    "enum": [
                        "OSDefault",
                        "RoundRobin",
                        "Random"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.SimSelectionMode"
                        }
                    ]
                },
                "work_hours_enabled": {
                    "description": "WorkHoursEnabled enables restricting message delivery to a configurable time window.",
                    "type": "boolean"
                },
                "work_hours_end": {
                    "description": "WorkHoursEnd is the end of the working hours window in HH:mm format (24-hour).",
                    "type": "string"
                },
                "work_hours_start": {
                    "description": "WorkHoursStart is the start of the working hours window in HH:mm format (24-hour).",
                    "type": "string"
                }
            }
        },
        "smsgateway.SettingsPing": {
            "type": "object",
            "properties": {
                "interval_seconds": {
                    "description": "IntervalSeconds is the interval between ping requests (in seconds).\nMust be at least 1 when provided.",
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "smsgateway.SettingsReceiver": {
            "type": "object",
            "properties": {
                "content_provider_enabled": {
                    "description": "ContentProviderEnabled enables monitoring the SMS content provider as a fallback for\ncarriers that intercept the SMS_RECEIVED broadcast.",
                    "type": "boolean"
                }
            }
        },
        "smsgateway.SettingsWebhooks": {
            "type": "object",
            "properties": {
                "internet_required": {
                    "description": "InternetRequired indicates whether internet access is required for webhooks.",
                    "type": "boolean"
                },
                "retry_count": {
                    "description": "RetryCount is the number of times to retry failed webhook deliveries.\nMust be at least 1 when provided.",
                    "type": "integer",
                    "minimum": 1
                },
                "signing_key": {
                    "description": "SigningKey is the secret key used for signing webhook payloads. Must not be used with Cloud Server.",
                    "type": "string"
                }
            }
        },
        "smsgateway.SimSelectionMode": {
            "type": "string",
            "enum": [
                "OSDefault",
                "RoundRobin",
                "Random"
            ],
            "x-enum-varnames": [
                "OSDefault",
                "RoundRobin",
                "Random"
            ]
        },
        "smsgateway.TextMessage": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "text": {
                    "description": "Text is the message text.",
                    "type": "string",
                    "maxLength": 65535,
                    "minLength": 1,
                    "example": "Hello World!"
                }
            }
        },
        "smsgateway.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "actual access token",
                    "type": "string"
                },
                "expires_at": {
                    "description": "time at which the access token is no longer valid",
                    "type": "string",
                    "format": "date-time"
                },
                "id": {
                    "description": "unique identifier for the access token",
                    "type": "string"
                },
                "refresh_token": {
                    "description": "refresh token",
                    "type": "string"
                },
                "token_type": {
                    "description": "type of the access token",
                    "type": "string"
                }
            }
        },
        "smsgateway.Webhook": {
            "type": "object",
            "required": [
                "event",
                "url"
            ],
            "properties": {
                "deviceId": {
                    "description": "The unique identifier of the device the webhook is associated with.",
                    "type": "string",
                    "maxLength": 21,
                    "example": "PyDmBQZZXYmyxMwED8Fzy"
                },
                "event": {
                    "description": "The type of event the webhook is triggered for.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/smsgateway.WebhookEvent"
                        }
                    ],
                    "example": "sms:received"
                },
                "id": {
                    "description": "The unique identifier of the webhook.",
                    "type": "string",
                    "maxLength": 36,
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "url": {
                    "description": "The URL the webhook will be sent to.",
                    "type": "string",
                    "example": "https://example.com/webhook"
                }
            }
        },
        "smsgateway.WebhookEvent": {
            "type": "string",
            "enum": [
                "sms:received",
                "sms:data-received",
                "sms:sent",
                "sms:delivered",
                "sms:failed",
                "sms:cancelled",
                "system:ping",
                "mms:received",
                "mms:downloaded",
                "app:started"
            ],
            "x-enum-comments": {
                "WebhookEventAppStarted": "Triggered when the application is started.",
                "WebhookEventMmsDownloaded": "Triggered when an MMS is downloaded.",
                "WebhookEventMmsReceived": "Triggered when an MMS is received.",
                "WebhookEventSmsCancelled": "Triggered when an SMS is cancelled.",
                "WebhookEventSmsDataReceived": "Triggered when a data SMS is received.",
                "WebhookEventSmsDelivered": "Triggered when an SMS is delivered.",
                "WebhookEventSmsFailed": "Triggered when an SMS processing fails.",
                "WebhookEventSmsReceived": "Triggered when an SMS is received.",
                "WebhookEventSmsSent": "Triggered when an SMS is sent.",
                "WebhookEventSystemPing": "Triggered when the device pings the server."
            },
            "x-enum-descriptions": [
                "Triggered when an SMS is received.",
                "Triggered when a data SMS is received.",
                "Triggered when an SMS is sent.",
                "Triggered when an SMS is delivered.",
                "Triggered when an SMS processing fails.",
                "Triggered when an SMS is cancelled.",
                "Triggered when the device pings the server.",
                "Triggered when an MMS is received.",
                "Triggered when an MMS is downloaded.",
                "Triggered when the application is started."
            ],
            "x-enum-varnames": [
                "WebhookEventSmsReceived",
                "WebhookEventSmsDataReceived",
                "WebhookEventSmsSent",
                "WebhookEventSmsDelivered",
                "WebhookEventSmsFailed",
                "WebhookEventSmsCancelled",
                "WebhookEventSystemPing",
                "WebhookEventMmsReceived",
                "WebhookEventMmsDownloaded",
                "WebhookEventAppStarted"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "SMSGate Web Dashboard API",
	Description:      "Web dashboard for the SMSGate. Provides a UI and API for managing devices, messages, webhooks, and settings.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
